# Generated by Django 4.2.9 on 2024-02-13 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackeagle', '0002_about_education_experience_projects_delete_acercade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='selfie',
            field=models.ImageField(blank=True, upload_to='about-images/'),
        ),
    ]
