# Generated by Django 4.2.9 on 2024-02-14 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackeagle', '0003_about_selfie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='selfie',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='education',
            name='image',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='image',
            field=models.URLField(),
        ),
    ]
