from .educationSerializer import EducationSerializer
from .experienceSerializer import ExperienceSerializer
from .projectsSerializer import ProjectsSerializer
from .aboutSerializer import AboutSerializer
from .badgeSerializer import BadgeSerializer
from .otherSerializer import OtherSerializer
from .extrasSerializer import ExtrasSerializer
from .contactSerializer import ContactSerializer